### ISSUE TITLE
Provide changelog

### ISSUE THREAD

**Issue by MurhafSousli** [tjoskar/ng2-lazyload-image#104]
Hi @tjoskar, Great module 👍, Can you provide Changelog file for future updates?

I would like to prepare a PR to add `window.service.ts`, `window.service.spec.ts` and Universal support

**Comment by tjoskar** [comment]
I added a changelog: https://github.com/tjoskar/ng2-lazyload-image/blob/master/changelog.md Feel free to add new features there :)
