### ISSUE TITLE
PixelateImage input feature

### ISSUE THREAD

**Issue by MurhafSousli** [tjoskar/ng2-lazyload-image#106]
I tried to implement pixelateImage example but I want it to be removed when lazyLoad loads, is it possible to implment `@Input() pixelateImage` in the directive to display it and to remove it when `lazyLoad` image is loaded?

**Comment by tjoskar** [comment]
Just to clarify, you want to include a reference to a image that we can remove after another images has been loaded. Eg.

```js
<img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD..." #pixelateImage>
<div lazyLoad="..." [pixelateImage]="pixelateImage"></div>
```

I suppose that would be quite easy to implement but I think that an event emitter would be more generic and more extendable: i.e.

```js
<img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD..." #pixelateImage>
<div lazyLoad="..." (loaded)="pixelateImage.remove()"></div>
```

**Comment by MurhafSousli** [comment]
I think that does the job

**Comment by tjoskar** [comment]
Just to clarify; this do not exist today but I will accept a pull request for it.

**Comment by MurhafSousli** [comment]
@tjoskar frankly I rolled back to the normal way of loading images after I compared both with and without the directive in a blog loading +15 images at a time, I found a notable decrease of loading speed instead of improving the UX, it seems that the directive would play well with a single big image, otherwise it should be done with a service worker.
