### ISSUE TITLE
CSS Class for yet to be Loaded Items

### ISSUE THREAD

**Issue by aboodz** [tjoskar/ng2-lazyload-image#110]
We use the following CSS to create fade-in effect for lazy loaded images.
```
img {
    transition: opacity 1s;
    opacity: 0;
}
img.ng2-lazyloaded {
    opacity: 1;
}
```
Unfortunately, this will cause all images inside the component to be hidden unless lazy loaded using ng2-lazyload. Sometimes, it is not really necessary to lazy load small images such as logos and sprites. Can we have a CSS class on yet to be loaded images, maybe `ng2-loading`, so we can have the fading effect like this: 
```
img.ng2-lazyloading {
    transition: opacity 1s;
    opacity: 0;
}
img.ng2-lazyloaded {
    opacity: 1;
}
```

**Comment by tjoskar** [comment]
The documentation is lacking on this but you should be able to use the class name `ng2-lazyloading` and after the image has been loaded the class name will be replaced with `ng2-lazyloaded`.

**Comment by rodrigoreal** [comment]
@tjoskar are you sure that `ng2-lazyloading` will be on the image while it is loading?
I'm trying to use that and no success, i even put a 100mb image to inspect the image properly and didn't saw that class.
But when the image is loaded the `ng2-lazyloaded` class apear on the image.

**Comment by tjoskar** [comment]
> @tjoskar are you sure that ng2-lazyloading will be on the image while it is loading?

You have to explicit add the class `ng2-lazyloading` and it will be removed after the image has been loaded.

e.g. Let's say you have the following image tag:
```html
<img src="some-image.jpg" [lazyLoad]="myImage" class="ng2-lazyloading">
```

After the image has been loaded, the class name will switch to `ng2-lazyloaded`.
```html
<img src="my-image.jpg" class="ng2-lazyloaded">
```
