### ISSUE TITLE
Lazy load is not triggered when data is filtered

### ISSUE THREAD

**Issue by skylarsutton** [tjoskar/ng2-lazyload-image#112]
Hello - thanks for the library. I'm having challenges with one specific use case.

We have a header, with an input box, and a content area with a PrimeNG datagrid. The datagrid is wrapped in a DIV with overflow-y set to auto. The input text gets fed to a PipeTransform which does a filter(...) on the datagrid's collection. 

Everything works as expected if we have no filter set... scrolling up and down on the DIV (scrollTarget) lazily loads the images. The issue is when we start keying in a filter. The grid filters the list of entries down, and entries that were on the bottom of the list (no image loaded yet) begin to show up, but their image never loads. 

I suspect it's because the DIV never actually scrolled, it resized as the items inside it grew and shrank... and eventually it shrank to the point that no scrollbar was needed so the scrollbar disappeared.  

Code sample below... thanks!

```html
<div id="navigationContainer" class="flexContainer">
  <div id="navigationHeader" class="navigationHeader">
    <input 
      pInputText 
      id="txtTtn" 
      type="text" 
      [(ngModel)]="navigationFilter" 
      (keyup.enter)="onEnterKey($event)"
      placeholder="{{'global.typeToNarrow'|translate}}"
      />
  </div>

  <div #graphicalNavigationScroller class="ui-g-nopad" style="overflow-y: auto">
    <p-dataGrid 
      id="navGrid"
      [value]="currentNavigationNode.childNodes | navigationFilterPipe: navigationFilter">
      
      <template let-navigationChildNode>
        <div class="ui-g-12 ui-md-3 ui-lg-2" [ngStyle]="{'min-width' : currentNavigationNode.childLevelIllustrationWidth+25+'px' }">
          <a class="thumbnail" (click)="navigate(navigationChildNode)" title="{{navigationChildNode.name}}">
            <img
              [scrollTarget]="graphicalNavigationScroller"
              [lazyLoad]="someSecretURL"
              width="{{currentNavigationNode.childLevelIllustrationWidth}}"
              height="{{currentNavigationNode.childLevelIllustrationHeight}}"
              />
            <div>{{navigationChildNode.name}}</div>
          </a>
        </div>
      </template>
    </p-dataGrid>
  </div>
</div>
```

**Comment by tjoskar** [comment]
> but their image *never* loads

Even if you start scrolling inside the div or is the div so small that you can't scroll?

This is not a easy problem to solve since we never know if the div has been resized. Can you trigger a function call after you have entered your filter criteria?

**Comment by skylarsutton** [comment]
The div is large enough that it does not require scrolling after filtering. Kind of hard to explain... see if this helps frame it: Imagine a div that allows us to see 20 items at a time. Initial collection loads with 100 items, items 1-20 display and images lazy load, items 21-100 are hidden below the fold/ below the scroll position and images are pending. Key "ta" into filter input, which reduces the 100 item collection to 5 items, but the items were #80, #81, #82, #83, and #84 in the original 100 item collection... therefore they currently have no image. Since the div can display 20 at a time, and there are only 5, the scrollbar disappears and all 5 are displayed.

Re: function... Yes, I could hook into ngModelChange and capture the filter input changing. Can I manually force lazyLoad to re-evaluate for the displayed items?

**Comment by tjoskar** [comment]
I see :) 

> Can I manually force lazyLoad to re-evaluate for the displayed items

Yes but it is not pretty ;)
You can manually trigger a scroll event:

```js
import { Component, Output, EventEmitter, ChangeDetectionStrategy, ElementRef, ViewChild } from '@angular/core';

@Component({
    selector: 'my-comp',
    templateUrl: 'my-view.html'
})
export class MyComponent {
    @ViewChild('graphicalNavigationScroller') graphicalNavigationScroller: ElementRef;

    ngOnChanges(changes) {
       if (filterHasChange) {
         graphicalNavigationScroller.dispatchEvent(new Event('scroll')); // This must however happen after angular has rerender the view
       }
    }
}
```

Do you understand my example?

**Comment by skylarsutton** [comment]
Yes - thank you. I was able to get something working by forcing a scroll event... I agree it's not pretty though. =)

Should I close the issue, or leave it open as a feature request (to handle differently in a future version)?

**Comment by tjoskar** [comment]
As I stated above; This is not a trivial problem. There is no easy way to detect this kind of changes. 

The only solution I can think of is to use a custom scrollObservable:

```js
const forceUpdate = new Subject();
const scrollObservable = 
  Observable.merge(
    Observable.fromEvent('scroll', graphicalNavigationScroller),
    forceUpdate
  );
```

And you can then trigger a force update with: `forceUpdate.next()`.


Another solution is to use [intersection observer](https://github.com/tjoskar/ng2-lazyload-image/issues/13) but that only works in Chrome right now.

I will close this issue for now.

**Comment by skylarsutton** [comment]
Thanks again for the help (and the library).
