### ISSUE TITLE
Feature: emit event when lazyLoadImage() is called

### ISSUE THREAD

**Issue by lhanneman** [tjoskar/ng2-lazyload-image#123]
I'm using ng2-lazyload-image as part of an "infinite scroller" where I don't want images to load until they come into view. 

I also have a standard paging bar above my image view container that displays Page X of X where a user could type a page number to jump to a specific page. 

Since ng2-lazyload-image is already monitoring which image comes into view via the scroll events, it'd be great if it could emit an event with that img element as it came into view, regardless of whether or not that image has been loaded already. This would allow the ability to know and make decisions based off which page is currently in view (i.e. update a "current page number" label without me having to write my own, similar scroll event handler).

I just want to make sure I'm not missing something - is it possible for me to access which image is in view today? Otherwise I could submit a pull request...

Thanks!

**Comment by tjoskar** [comment]
Hi,

There is no support for event emitting today.

 > Since ng2-lazyload-image is already monitoring which image comes into view via the scroll events, it'd be great if it could emit an event with that img element as it came into view
This is something that should be pretty easy to add support for in ng2-lazyload-image. It should just be to add a event emitter in the directive that emits a new value for every [next event](https://github.com/tjoskar/ng2-lazyload-image/blob/4dfbc601752fb92deb62df09e55294af495ce7f9/src/lazyload-image.directive.ts#L35)

> ... regardless of whether or not that image has been loaded already.
This is however something that can't be done in ng2-lazyload-image. After the image has been loaded the directive unsubscribe any scroll listener for performance reasons. The directive will never know when the image is going out of viewport or coming back in for that matter.

**Comment by lhanneman** [comment]
Yeah.. I cloned the repo and was messing with it locally and realized pretty quick that 

> ... regardless of whether or not that image has been loaded already.

wasn't going to work. Maybe something to think about for the future.

**Comment by tjoskar** [comment]
> Maybe something to think about for the future.

I don't know. I don't think that the average user wants to keep a scroll listener for every image after the image has been loaded. It is quite a performance cost.

**Comment by tjoskar** [comment]
Thanks for your feedback. I will close this issue but feel free reopen it.
