### ISSUE TITLE
Images in a hidden tab are not lazy loaded

### ISSUE THREAD

**Issue by daangeerdink** [tjoskar/ng2-lazyload-image#126]
Hi there,

I have a situation where I have 3 Bootstrap tabs with content and images in them. If the tab is active (showing), lazy loading works as expected and only loads images when they come into view. 

However, all of the images that are in the non-active (hidden) tabs are not lazy loaded and are loaded immediately. 

Is there a solution for this?

Thanks

**Comment by tjoskar** [comment]
Hi, 

That sounds strange. How did you verify that behaviour? And what browser are you using?

I just tried to open up the [example page](http://tjoskar.github.io/ng2-lazyload-image/fade-in-image) in the a background tab (right click => open in new tab) and it seams to works as expected in chrome.

**Comment by daangeerdink** [comment]
@tjoskar Sorry I wasn't clear enough, I meant images that are in [Bootstrap tabs](http://getbootstrap.com/javascript/#tabs) are not being lazy loaded.

**Comment by tjoskar** [comment]
aaa, I see... that is a tuff one. Right now we don't really know if the image is visible, just that it is some somewhere in the viewport.

Maybe a longshot, but can you try:

```html
<img #image *ngIf="image.offsetParent !== null" [lazyLoad]="youImage">
```

or if you have it in a loop:

```html
<div #imageContainer>
 <img *ngIf="imageContainer.offsetParent !== null" [lazyLoad]="image" *ngFor="let image in images">
</div>
```

**Comment by daangeerdink** [comment]
@tjoskar That seems to work, not a bad solution :) Thanks for your help!

**Comment by tjoskar** [comment]
Glad to help!
