### ISSUE TITLE
ionic build brower --prod error

### ISSUE THREAD

**Issue by chenwenhao1992** [tjoskar/ng2-lazyload-image#127]
run ionic build brower --prod 

i'm run ionic build brower --prod  they are  successful;

but i try throw them in my ftp serve and input my ftp address in chrome

chrome console.log error:

url_search_params.js:156 Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open 'E:\workspace\01Code\h5\webapp\node_modules\.2.4.0@ng2-lazyload-image\src\lazyload-image.directive.ngfactory.js'
    at Error (native)
    at Error (native)
    at Object.<anonymous> (http://192.168.10.115:8000/build/main.js:18:16700)
    at e (http://192.168.10.115:8000/build/main.js:1:101)
    at Object.<anonymous> (http://192.168.10.115:8000/build/main.js:25:29190)
    at e (http://192.168.10.115:8000/build/main.js:1:101)
    at Object.<anonymous> (http://192.168.10.115:8000/build/main.js:26:14759)
    at e (http://192.168.10.115:8000/build/main.js:1:101)
    at Object.<anonymous> (http://192.168.10.115:8000/build/main.js:49:7773)
    at e (http://192.168.10.115:8000/build/main.js:1:101)
    at Object.<anonymous> (http://192.168.10.115:8000/build/main.js:40:14315)
    at e (http://192.168.10.115:8000/build/main.js:1:101)

ionic info:

Ionic Framework Version: 2.0.0-rc.6
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.2.0
Xcode version: Not installed

package.json

{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.7",
    "ion-multi-picker": "^1.1.5",
    "ionic-angular": "2.0.0-rc.6",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "ng2-lazyload-image": "^2.4.0",
    "ng2-uploader": "^2.0.0",
    "rxjs": "5.0.0-beta.12",
    "sw-toolbox": "^3.4.0",
    "ts-md5": "^1.2.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^1.1.1",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-statusbar",
    "cordova-plugin-splashscreen",
    "cordova-plugin-device",
    "cordova-plugin-console",
    "ionic-plugin-keyboard",
    "cordova-plugin-whitelist"
  ],
  "cordovaPlatforms": [],
  "description": "sports-ip: An Ionic project"
}

please help me

thanks!

**Comment by tjoskar** [comment]
Hi,

I'm not sure what `run ionic build brower --prod` is doing but I guess it has something to do with AOT compilation.

Does this folder exist and what does it contain in such case? `E:\workspace\01Code\h5\webapp\node_modules.2.4.0@ng2-lazyload-image`? 

It feels like `run ionic build brower --prod` is doing something oddly or that you miss to include some files when to uploaded them.

**Comment by chenwenhao1992** [comment]
@tjoskar 

i fixed it!

1.find lazyload-image.directive.ngfactory.ts in node_mudules.
2.delete it.
3.run ionic build browser --prod

it's worked!

Actually lazyload-image.directive.ngfactory.ts is unnecessary to me.
