### ISSUE TITLE
Ionic2 content init working, load image window scroll event not triggering

### ISSUE THREAD

**Issue by segersrobbert** [tjoskar/ng2-lazyload-image#2]
I'm trying to use your directive inside an ng2-ion2 project and it seems the scroll event is not being triggered. I've looked in your source code and it seems to me that the observable event is not being triggered. I think `Observable.fromEvent(window, 'scroll')` should be adjusted to an Ionic2 scroll event to make it work. 
### Reproduce

1. Install & import directive (Ionic2 project)
2. Template: `<img [src]="defaultImage" [lazyLoad]="image" [offset]="offset">`
3. Class constructor: 

```
this.defaultImage = 'https://www.placecage.com/1000/1000';
this.image = 'https://images.unsplash.com/photo-1443890923422-7819ed4101c0?fm=jpg';
this.offset = 100;
```
### Result
Initial default images are being shown, the lazyload images are not loaded, so that's working.
But the scroll event is not being triggered so lazyloading new images is not working in Ionic2.

Thank you.

**Comment by tjoskar** [comment]
Hi,

You are right. `window` will not trigger any `scroll`-event in a `ng2-ion2` project.

I have updated the code (d763b7c15031dea9852621be2b6b7ec1c45084ab) with the ability to change what element we want to listen on `scroll`-events, eg:
```html
<div style="height: 100px; overflow-y: scroll;" #container>
    <img
        [src]="defaultImage"
        [lazyLoad]="image"
        [offset]="offset"
        [scrollTarget]="container">
</div>
```

I created a demo project:
```bash
$ ionic start ionic-lazy-load-images --v2
$ npm install ng2-lazyload-image@1.1.0 --save
```
and updated:

`ionic-lazy-load-images/app/pages/page1/page1.js`: 
```javascript
import { Page } from 'ionic-angular';
import { LazyLoadImageDirective } from 'ng2-lazyload-image';

@Page({
  templateUrl: 'build/pages/page1/page1.html',
  directives: [ LazyLoadImageDirective ]
})
export class Page1 {
  constructor() {
    this.defaultImage = 'https://www.placecage.com/1000/1000';
    this.image = 'https://images.unsplash.com/photo-1443890923422-7819ed4101c0?fm=jpg';
    this.offset = 100;
  }
}
```

`ionic-lazy-load-images/app/pages/page1/page1.html`:
```html
<ion-navbar *navbar>
  <ion-title>Tab 1</ion-title>
</ion-navbar>

<ion-content padding class="page1" #container>
  <h2>Welcome to Ionic!</h2>
  <p style="height: 1000px;">
    This starter project comes with simple tabs-based layout for apps
    that are going to primarily use a Tabbed UI.
  </p>
  <img [src]="defaultImage" [lazyLoad]="image" [offset]="offset" [scrollTarget]="container.scrollElement">
</ion-content>
```

And it seems to work fine :)

**Comment by segersrobbert** [comment]
Works! Awesome, thanks.
(Note `#container` has to be placed on an `ion-content` tag)

**Comment by 3dd13** [comment]
should use getter method for the scrollTarget

    <img
      [src]="defaultImage"
      [lazyLoad]="image"
      [offset]="offset"
      [scrollTarget]="container.getScrollElement()" />
