### ISSUE TITLE
sometimes getScrollListener() returns the same scrollListener with different scrollTarget

### ISSUE THREAD

**Issue by 3dd13** [tjoskar/ng2-lazyload-image#23]
possible that the scrollTarget is not comparable (always equals regardless)
e.g. different ion-content scrollContent in Ionic 2 consider the same key in the following code

    if (scrollTarget in scrollListeners) {
        return scrollListeners[scrollTarget];
    }

**Comment by tjoskar** [comment]
This problem should be solved by version 2.2.0. Please feel free to reopen if you encounter any problems.
