### ISSUE TITLE
Problem importing LazyLoadImageDirective

### ISSUE THREAD

**Issue by rtozati** [tjoskar/ng2-lazyload-image#33]
Hi,

I had a problem importing the directive in my ts file.

In the usage block ("https://github.com/tjoskar/ng2-lazyload-image#usages"), you say to import like the line below, but It did not work on my project:
`import { LazyLoadImageDirective } from 'ng2-lazyload-image';`

It worked for me when I imported using the line below, using the same import pattern you have used in your example:
`import { LazyLoadImageDirective } from 'ng2-lazyload-image/src/lazyload-image.directive';`

Do you think I am doing something wrong?

Thanks,
Ricardo

**Comment by tjoskar** [comment]
Hi,

Are you using `systemjs` or what build tool are you using?

**Comment by rtozati** [comment]
Hi, 

I am using **systemjs**!

**Comment by tjoskar** [comment]
Hi, sorry for the delay.

Can you give me your system js config? 
Have you some binding for `node_modules` like:

```javascript
paths: {
  '*': 'node_modules/*',
  'app/*': 'app/*'
},
```

**Comment by tjoskar** [comment]
Feel free to reopen the issue if you still have any issue with the library.

**Comment by jnah** [comment]
i have the same issue width systemJS (ng2.0.0)
