### ISSUE TITLE
<image> selector not working in IE11 and Edge

### ISSUE THREAD

**Issue by mpavel** [tjoskar/ng2-lazyload-image#34]
This is not really an issue per se, but I wanted to document this here for others, and maybe the docs will be updated to reflect this.

It appears that IE11 and Microsoft Edge browsers are not playing well with having `image` as a selector. After implementing the example code and using `<image ...></image>` I tested in these 2 browsers and saw no images displayed (they were requested by the browsers however). This behaviour happens also on demo page.

Checking the Dev Tools (F12) I noticed that `<image>` tags were rewritten as `<img>` tags, not sure why.

I updated the component to use a different selector. I picked `<lz-image>` and this eliminates the issue in these 2 browsers.

**Comment by tjoskar** [comment]
You are absolutely right. I should not use html element like [image](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image). I'm actually surprised it works in chrome and firefox now when you pointed it out.

Thanks!
