### ISSUE TITLE
Use error image if http request fails rather than default image

### ISSUE THREAD

**Issue by freezing** [tjoskar/ng2-lazyload-image#35]
I think that this directive should include one more input, something like [errorImage].

The idea behind this is to have loader image, e.g. "loading.gif" as default image.
Lazily loaded image should be the one we want. However, this image might not exist or the http request might fail, which is out of our control. Currently, if http request fails, it will use default image (the one that is specified in src), but that is bad if we wanted to show loader image initially.

I might be wrong here and don't see the correct way to do. If that is the case please correct me?

Otherwise, would you mind adding a new input to the directive, i.e. "errorImage" where the behavior should stay as it is at the moment if errorImage is null, otherwise it should use errorImage if http request fails.

Input example would be:

`<img [src]="loader.gif" [lazyLoad]="our_goal_img.png" [errorImg]="no_image.png" offset="100" />`

**Comment by tjoskar** [comment]
Thanks for your feedback. I see the problem and I agree with you.

Do you want to submit a pull request? If not, I will fix it during the weekend (when I upgrade angular to RC6 and add some unit test).

**Comment by freezing** [comment]
I will try to make a pull request tonight or tomorrow.

**Comment by freezing** [comment]
I have written the fix. Can you give me the permissions to push the branch and create the pull request?
