### ISSUE TITLE
Can't bind to 'lazyload' since it isn't a known native property

### ISSUE THREAD

**Issue by audacitus** [tjoskar/ng2-lazyload-image#37]
I'm running an existing Ionic 2 project (2.0.0-beta.11, using Angular 2.0.0-rc.4). Installed and setup, but keep getting the following error (The error occurs on runtime. No issue when compiling)

![image](https://cloud.githubusercontent.com/assets/15983058/18389109/41491ec0-769c-11e6-8393-92f4ae8948a6.png)
### Steps I took:

**Ran Npm:**
`$ npm install ng2-lazyload-image --save`

**Imported into my component:**
`import { LazyLoadImageDirective } from 'ng2-lazyload-image';`

**Set Directives:**
`directives: [ LazyLoadImageDirective ]`

**Set variables and defaults:**

```
export class PostComponent {
defaultImage: any = 'build/assets/preloader.gif';
offset = 100;
@Input() feedImage: string = 'build/assets/blank-default-feed-bg.png';
}
```

**In my template:**
`<img [src]="defaultImage" [lazyload]="feedImage" [offset]="offset" class="feed-image">`

Maybe there's something I'm overlooking, but I can't seem to see what it is.

**Comment by tjoskar** [comment]
Hi,

I can't reproduce the problem. What version of ng2-lazyload-image are you using? Is the project open source so I can take a look at it?

### Steps I took:
```
$ npm install -g ionic@beta
$ ionic --version
2.0.0-beta.37
$ ionic start ionic-lazy-load-images --v2
$ cd ionic-lazy-load-images
$ npm install ng2-lazyload-image@2.1.1 --save
$ ionic serve
```

#### Updated the code:

`app/pages/home/home.html:
```html
<ion-header>
  <ion-navbar>
    <ion-title>Home</ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding class="home" #container>
  <h2>Welcome to Ionic!</h2>
  <p>
    This starter project comes with simple tabs-based layout for apps
    that are going to primarily use a Tabbed UI.
  </p>
  <p style="height: 1000px;">
    Take a look at the <code>app/</code> directory to add or change tabs,
    update any existing page or create new pages.
  </p>
  <img
    style="height: 1099px;"
    [src]="defaultImage"
    [lazyLoad]="image"
    [offset]="offset"
    [scrollTarget]="container._scroll._el">
</ion-content>
```

`app/pages/home/home.ts:
```javascript
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { LazyLoadImageDirective } from 'ng2-lazyload-image';

@Component({
  templateUrl: 'build/pages/home/home.html',
  directives: [ LazyLoadImageDirective ]
})
export class HomePage {
  defaultImage = 'https://www.placecage.com/1000/1000';
  image = 'https://hd.unsplash.com/photo-1441765425173-8fd330fb4a02';
  offset = 100;

  constructor(private navCtrl: NavController) {
  }
}
```

And it works fine :)

HOWEVER, since ionic is using tabs (per default) and adding `display: none` on the scroll container, it makes it nearly impossible to determine if the image is initially in viewport or not. It should be nice to use something like [intersection observer](https://github.com/tjoskar/ng2-lazyload-image/issues/13) but it only works in Chrome and if you targeting iOS you are going to use Safari :/

One solution is however to check if the image is hidden (eg: `el.offsetParent === null`) but when the image get visible again, `ng2-lazyload-image` will not receive any notification and IF the image is in the viewport, the image will not show up before the user starts to scrolling. You could however use `*ngIf` for that:

```html
<img
    *ngIf="container._scroll._el.offsetParent !== null"
    style="height: 1099px;"
    [src]="defaultImage"
    [lazyLoad]="image"
    [offset]="offset"
    [scrollTarget]="container._scroll._el">
```

But that doesn't look any good :/


So.. you might or might not be able to use `ng2-lazyload-image` in your ionic app (depending on your layout) but you should *not* get any runtime errors.

**Comment by StanFaas** [comment]
You made a typo.
It's [lazyLoad], not [lazyload]

Cheers :)

**Comment by audacitus** [comment]
That sounds embarrassingly simple. <facepalm>
I'll be upgrading to the rc1 and try it out. Thanks.

**Comment by tjoskar** [comment]
@StanFaas, nice catch!

**Comment by splurtcake** [comment]
I'm having this same problem with angular 2 universal
`Can't bind to 'lazyLoad' since it isn't a known property of 'img'`

lazy-image.component.html
```<div class="lazy_image">
    <img [src]="defaultImage" [lazyLoad]="image" [offset]="offset">
</div>```


app.module.ts
```@NgModule({
	declarations: [
		AppComponent,
	],

	providers: [
		JsonpModule,
		ApiMocksProvider,
		BaseRequestOptions,
		MockBackend
  ],

	imports: [
		...ROUTED_MODULES,
		FormsModule,
		LazyLoadImageModule,		
		SharedModule,
	]
})```

lazy-image.component.ts
```import {
    Component,
    Input,
    Inject,
    ChangeDetectionStrategy,
    ViewEncapsulation
} from '@angular/core';

@Component({
	changeDetection: ChangeDetectionStrategy.Default,
	encapsulation: ViewEncapsulation.None,
	selector: 'lazy-image',
	styleUrls: [ './lazy-image.component.scss' ],
	templateUrl: './lazy-image.component.html'
})

export class LazyImageComponent {

    defaultImage = 'https://www.placecage.com/1000/1000';
    image = 'https://images.unsplash.com/photo-1443890923422-7819ed4101c0?fm=jpg';
    offset = 100;

    constructor() {
        
    }
}
````

Where am I going wrong?

**Comment by splurtcake** [comment]
Okay so I've changed the template to be inline, instead of a separate file and that worked a little better, however the output on the screen is

`<img [src]=require('./defaultImage') [lazyLoad]=require('./image') [offset]=require('./offset')>`

**Comment by thought2tech** [comment]
I am getting the same error for Angular 4 application.

**Comment by Jayakarreddy** [comment]
<img width="1273" alt="123" src="https://user-images.githubusercontent.com/32204780/50469382-2597d380-09d2-11e9-8687-a87897ddc1a4.png">
I'm getting the same error how can I solve it.
