### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by jose2007kj** [tjoskar/ng2-lazyload-image#46]
sir, i am getting this error ........where i might be going wrong

**Comment by jose2007kj** [comment]
when i removed the peer dependencies inside package.json files......this error is gone........

**Comment by tjoskar** [comment]
Hi @jose2007kj,

I'm only supporting angular version 2.0.0-rc6 and higher due to angulars braking change with module and how components are handling directives. 
Meaning you have to use angular at version 2.0.0-rc6 or higher to be able to use the latest version of this directive. You could however install an older version:

```
npm install ng2-lazyload-image@2.1.1
``
which works with angular 2.0.0-rc4. You can see here how to use it for an older version here: https://github.com/tjoskar/ng2-lazyload-image/blob/76a7fa2ced63ecddc0186b2f0d33929574076594/README.md

**Comment by jose2007kj** [comment]
thankyou sir........i will try that
sir......one doubt ........if i replace rc5 with rc6 in dependencies(in package.json ).......will everthing work fine?

**Comment by tjoskar** [comment]
> if i replace rc5 with rc6 in dependencies(in package.json )

It depends. Are you using [modules](https://angular.io/docs/ts/latest/guide/ngmodule.html)? The angular team introduced modules in rc5 and in rc6 they remove "@Component.directives and @Component.pipes" (see: https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes-1).
Meaning you can no longer use the following api:

```
@Component({
    selector: 'image',
    template: `
        <img [src]="defaultImage" [lazyLoad]="image" [offset]="offset">
    `,
    directives: [ LazyLoadImageDirective ] // This is no longer supported in angular rc6
})
class ImageComponent {
    defaultImage = 'https://www.placecage.com/1000/1000';
    image = 'https://images.unsplash.com/photo-1443890923422-7819ed4101c0?fm=jpg';
    offset = 100;
}
```

If you are using modules (@NgModule) you can probably just upgrade to rc6 or even the finial version (2.0.0). You can always install a newer version of angular and try to build the project. If it don't work you can always just downgrade angular again (and maybe remove node_module folder and run `npm install` one more time).

**Comment by tjoskar** [comment]
If you are using modules, you should upgrade ng2-lazyload-image to version 2.2.1 (`npm install ng2-lazyload-image@2.2.1`). I just publish a updated version.

**Comment by jose2007kj** [comment]
ok.........thankyou sir
