### ISSUE TITLE
Can't use this package with ngc to use AOT compilation

### ISSUE THREAD

**Issue by dhardtke** [tjoskar/ng2-lazyload-image#49]
Hey,

great package. Can't use it with `ngc` though:

`Error: Unexpected value 'LazyLoadImageDirective' declared by the module 'AppModule'`

The required metadata json files are missing, maybe this guide helps: https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad

**Comment by tjoskar** [comment]
Hi,

Interesting! I have not looked at AOT-compiling yet but it is absolutely something that this package should support! I will have a look at it tomorrow!

Thanks!

**Comment by dhardtke** [comment]
Thanks or the fast commit.
Getting `
Error: Error at node_modules/ng2-lazyload-image/src/scroll-listener.ts:24:16: Type '{}' is not assignable to type 'Observable<any>'.` now.

**Comment by tjoskar** [comment]
Did you use the package from commit 13640472 (this commit should give errors) or eca01545 (this commit should not give any error)? Anyhow, I have not test it yet so I can't guarantee that it will work.

**Comment by dhardtke** [comment]
I am using the package from https://github.com/tjoskar/ng2-lazyload-image/commit/eca01545b0ba1825582cd73255f9a1c09e32a3b2.

Also, I get the same error message in webpack :(
`scroll-listener.ts:24:15
Type '{}' is not assignable to type 'Observable<any>'.
  Property '_isScalar' is missing in type '{}'.`

**Comment by dhardtke** [comment]
Please have a look at my PR - for me it is working with that change.

**Comment by dhardtke** [comment]
Okay, that's weird: If I'm using rollup after the ngc compilation I get this error:
`Module node_modules\ng2-lazyload-image\index.js does not export LazyLoadImageModule (imported by app\app.module.js)`

**Comment by dhardtke** [comment]
Weird. I can safely ignore that message, it is compiling after running `ngc` again.

**Comment by dhardtke** [comment]
ping @tjoskar

**Comment by tjoskar** [comment]
Hi @dhardtke, sorry for the late response. I have been on vacation without internet connection . 

Okey, first of:
You should never get error like: `scroll-listener.ts:24:15 Type '{}' is not assignable to type 'Observable<any>'. Property '_isScalar' is missing in type '{}'.`. This indicates that some `.ts` files is included in the npm package which they should not be. 

Can you take a look in your `node_modules/ng2-lazyload-image/src` folder to see if you have any `.ts` files?

> Okay, that's weird: If I'm using rollup after the ngc compilation I get this error:
Module node_modules\ng2-lazyload-image\index.js does not export LazyLoadImageModule (imported by app\app.module.js)

It is weird. I just publish a beta version of `ng2-lazyload-image` (for simpler installs) and tried to reproduce the problem by cloning https://github.com/qdouble/angular-webpack2-starter and then adding this project (ng2-lazyload-image):
```
$ git clone https://github.com/qdouble/angular-webpack2-starter.git && cd angular-webpack2-starter
$ npm install ng2-lazyload-image@2.2.2-beta.4 --save
```

I then updated `src/app/app.module.ts` to import `LazyLoadImageModule`:
```javascript
import { LazyLoadImageModule } from 'ng2-lazyload-image';

...

imports: [
    APP_IMPORTS,
    BrowserModule,
    HttpModule,
    LazyLoadImageModule
],
...
```

and then using the directive in `src/app/app.component.html`:
```html
<img src="https://www.placecage.com/1000/1000" lazyLoad="https://hd.unsplash.com/photo-1441765425173-8fd330fb4a02" offset="0">
```

and at last building the project:
```
$ npm run compile:aot && npm run prodserver
```
and it works :) But having said that; `angular-webpack2-starter` do not use rollup. Can you give `ng2-lazyload-image@2.2.2-beta.4` a try with your rollup configuration?

**Comment by dhardtke** [comment]
I stopped using rollup so no, I can't :D

And I had the .ts files in my node_modules/ng2-lazyload-image folder because I had to download that specific version to get AOT working. The "normal" npm installed version is the one where it is broken.

Before said commit (https://github.com/tjoskar/ng2-lazyload-image/commit/eca01545b0ba1825582cd73255f9a1c09e32a3b2) I would get the `Module node_modules\ng2-lazyload-image\index.js does not export LazyLoadImageModule (imported by app\app.module.js)` error.

I tried 2.2.2-beta.4 and it's working like a charm! And btw.: Even that beta includes the .ts files so I am not sure why you said there shouldn't be any.

**Comment by tjoskar** [comment]
> And btw.: Even that beta includes the .ts files so I am not sure why you said there shouldn't be any.

Are you sure? `.d.ts`-files should be included but `.ts` should not. I can not find any `.ts` files when I install `ng2-lazyload-image` from npm. Can you try to remove the ` node_modules\ng2-lazyload-image` folder and run `npm install ng2-lazyload-image@2.2.2-beta.4` once again and list the `.ts`-files you get (if you receive any)?

– Thanks.

**Comment by dhardtke** [comment]
You're right, I was wrong about the .ts files.

Sorry about that. So it all works with 2.2.2-beta.4 - will you publish it as new stable version?

**Comment by tjoskar** [comment]
Yes, it has now been published 🎉
