### ISSUE TITLE
Image wont show again if used with Angular Router

### ISSUE THREAD

**Issue by digitalkaoz** [tjoskar/ng2-lazyload-image#52]
if i initially load a url with lazyload images, they show up...

if i navigate away and back, the are not shown again (the src attribute on the `<img>` is missing

**Comment by digitalkaoz** [comment]
im using angular 2.0.2 and router 3.0.2

**Comment by tjoskar** [comment]
Hi,

I can not reproduce the error. I have update the [example](https://github.com/tjoskar/ng2-lazyload-image/blob/205d030101598d198eb73b48e7e88612ac2e0d58/example/app.module.ts#L21-L31) to use angular router and you can see live demo here: http://tjoskar.github.io/ng2-lazyload-image/default-image

**Comment by tjoskar** [comment]
I'm closing this.
