### ISSUE TITLE
Ionic 2 Lazy loading not working on scroll

### ISSUE THREAD

**Issue by partharanjan** [tjoskar/ng2-lazyload-image#62]
Hi,
When I am trying to scroll the page, Image is not updating.
I am using latest version of ionic and  ng2-lazy-load library

**Comment by tjoskar** [comment]
Hi,

You probably have to change the scroll target. Ionic have a static height on the `window` and uses an inner container for the scroll. 

See #1 and #2 for example:
```html
<ion-content padding class="page1" #container>
  <h2>Welcome to Ionic!</h2>
  <p style="height: 1000px;">
    This starter project comes with simple tabs-based layout for apps
    that are going to primarily use a Tabbed UI.
  </p>
  <img [src]="defaultImage" [lazyLoad]="image" [offset]="offset [scrollTarget]="container.scrollElement">
</ion-content> 
```

**Comment by tjoskar** [comment]
Closing this, please reopen if you still have any issues.

**Comment by fryck** [comment]
You always you simpler example, but what about a more complex example, like :

`<ion-content padding class="page1" #container>
  <h2>Welcome to Ionic!</h2>
  <p style="height: 1000px;">
    This starter project comes with simple tabs-based layout for apps
    that are going to primarily use a Tabbed UI.
  </p>
  <CustomElement></CustomElement>
</ion-content> `

CustomElement contain a lazy load img : 

`<img [src]="defaultImage" [lazyLoad]="image" [offset]="offset [scrollTarget]="container.scrollElement">`

How process in this case ?

And you can imagine more components level, how deal with more parents components levels ?
