### ISSUE TITLE
Ionic Build ::  Property '_el' is private

### ISSUE THREAD

**Issue by sidjoshi001** [tjoskar/ng2-lazyload-image#75]
Hi,

this is awesome when I serve my Project, but when I am trying to build then facing this issue.

 **Property '_el' is private and only accessible within class 'ScrollView'.**

Code example as below.

```html
<ion-content #container>
<div>
<div class="bootstrap-row">
<div class="col col-50" *ngFor="let product of products">
<img *ngIf="container._scroll._el.offsetParent !== null" [lazyLoad]="imagePath+product.image" src="img/others/load-product-thumb.png" [scrollTarget]="container._scroll._el">
</div>
</div>
</div>
</ion-content>
```

**Comment by comfortme** [comment]
this solved my https://github.com/tjoskar/ng2-lazyload-image/issues/73 issue but i didnt try to build.
but it is not related to lazyload library more like a ionic 2 issue i guess.
but of course i think this library should handle ionic 2 apps by default.

**Comment by tjoskar** [comment]
> when I am trying to build then facing this issue

@sidjoshi001, When you say "build", do you mean [AoT compilation](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html)? 

There are unfortunately some compatibility problems with this project and ionic. `*ngIf="container._scroll._el.offsetParent !== null" [scrollTarget]="container._scroll._el"` is not optimally but it's the only (current) solution that I'm aware of.

> but of course i think this library should handle ionic 2 apps by default.

I agree. I've however never used ionic so my ionic knowledge is limited, but I started to look at its source code and found [this line](https://github.com/driftyco/ionic/blob/5bbbfb2b0057836ae2bfd57a73ae75b9e31cb6bb/src/components/infinite-scroll/infinite-scroll.ts#L248); it looks like ionic has its own scroll listener.
My suggestion is to refactoring the current directive so that it only contains Angular specific code and that all logic is in its own file lib-file. Thus we create a new ionic specific directive e.g.`lazyLoadIonic` (or something) which would looks something like this:

```typescript
@Directive({
  selector: 'lazyLoadIonic'
})
export class LazyLoadIonic {
  @Input('lazyLoad') lazyImage;
  @Input('src') defaultImg;
  @Input('errorImage') errorImg;
  @Input() offset

  constructor(@Host() private _content: Content, private el: ElementRef) {}

  ngOnInit() {
    lazyLoadImage(
      this.lazyImage,
      this.defaultImg,
      this.errorImg,
      this.offset,
      this.el,
      this._content.ionScroll
    ).subscribe();
  }

}

@Directive({
    selector: '[lazyLoad]'
})
export class LazyLoadImageDirective {
  @Input('lazyLoad') lazyImage;
  @Input('src') defaultImg;
  @Input('errorImage') errorImg;
  @Input() scrollTarget;
  @Input() offset

  constructor(private el: ElementRef) {
      this.elementRef = el;
  }

  ngOnInit() {
    lazyLoadImage(
      this.lazyImage,
      this.defaultImg,
      this.errorImg,
      this.offset,
      this.el,
      getScrollListener(this.scrollTarget)
    ).subscribe();
  }
}

function lazyLoadImage(lazyImage, defaultImg, errorImg, offset, elementRef, scrollObservable) {
  scrollObservable.filter(() => isVisible(elementRef, offset))
    .take(1)
    .switchMap(() => loadImage(lazyImage))
    // and so on
}
```

My time is rather limited right now so I don't know when I get the time to look into this but PR is always welcome :)

**Comment by sidjoshi001** [comment]
@tjoskar Hey thanks for this post, Did you create this directive for Ionic2 because I could not find in this project..!! Waiting for reply

**Comment by tjoskar** [comment]
@sidjoshi001, I did not :/ I have not found the time yet but I might get some spare time this weekend.

**Comment by sidjoshi001** [comment]
@tjoskar Still waiting for your reply...!! publish for ionic2

**Comment by tjoskar** [comment]
@sidjoshi001, I'm working on it right now but I do not know when I have a functional solution :/

**Comment by tjoskar** [comment]
@sidjoshi001, my first solution attempt with `@Host() private _content: Content` did not work. We can only get access to `Content` from a parent component and this lazyload directive is a child leaf.

I added however a new property `scrollObservable` which you can use to start subscribe for ionic scroll events, like this:

```html
<ion-content #container padding>
  <img src="https://www.placecage.com/1000/1000" [lazyLoad]="lazyLoadImage" [scrollObservable]="container.ionScroll" />
</ion-content>
```

Try it in version 2.3.1: `$ npm install ng2-lazyload-image@2.3.1` and let me know what you think or if you run into any problems.

**Comment by sidjoshi001** [comment]
@tjoskar thanks for effort...

but am getting following error

Lexer Error: Unexpected character [о] at column 12 in expression [container.iоnScroll]' at column 13 in [container.iоnScroll]

my code is below..

```
<ion-content class="content"  #container>
	<ion-spinner class="page-loading" color="purple" *ngIf="!categories"></ion-spinner>
	<div *ngIf="categories">
		<div class="categories" *ngFor="let category of categories.categories; let i = index ">
			<div class="title" id="{{i}}">{{ category.name }}</div>
			<div class="bootstrap-row">
				<div class="col col-33 siblings" *ngFor="let sibling of category.siblings; let odd = odd" [ngClass]="odd ? 'odd' : null" (click)="toProductList(sibling)">
					<img src="assets/img/others/load-300-300.png" [lazyLoad]="categories.imagePath+sibling.image" [scrollObservable]="container.iоnScroll" />
					<div class="name">{{ sibling.name | trancate:25 }}</div>
				</div>
			</div>
		</div>	
	</div>
</ion-content>
```

**Comment by tjoskar** [comment]
@sidjoshi001, maybe a long shot but the first `o` in `iоnScroll` is not a ordinary `o` in the code you included. If I copy the `о` and get the charcode for it (eg. `'о'.charCodeAt(0)` in javascript) I get 1086 but an ordinary `o` has charcode 111. So, can you try to remove `container.iоnScroll` in your code and type it by hand again?

**Comment by sidjoshi001** [comment]
Yo... @tjoskar thanks, working very well..!!

**Comment by comfortme** [comment]
the real issue here is @tjoskar how did you able see that and @sidjoshi001 how did you able to do that :smiley:

**Comment by tjoskar** [comment]
@sidjoshi001, great! I'm not satisfied with the solution but I can't come up with a better one right now. Pull requests is always welcome :)

@comfortme, I thought that the `о` looked strange (it deviate more in my email client) and if you take a look at the error message, it says that char at position 12 in the string `container.iоnScroll` is unexpected :)

**Comment by tjoskar** [comment]
Closing this with https://github.com/tjoskar/ng2-lazyload-image/commit/1e0e9d1df2c6c46c7ebd820b6a5129ab67a38b39
