### ISSUE TITLE
Lazy Loading inside a Scrollable area

### ISSUE THREAD

**Issue by thesunnypro** [tjoskar/ng2-lazyload-image#96]
Thanks for this wonderful library. I cannot get it to work with scrollable div unfortunately. 

Using this below code doesn't works. 

`scrollTarget = this.document.getElementById('scrollableDiv');`

Any light on how I can use the config in better way?

An example would have been great though.

P.S: I am not using ionic.

**Comment by tjoskar** [comment]
Hi,

Just to be clear, have you verify that `scrollTarget` is the actual scroll target? For instance by:
```
scrollTarget = this.document.getElementById('scrollableDiv');
console.log(scrollTarget);
scrollTarget.addEventListener('scroll', () => console.log('Im scrolling'));
```

Second, are you passing the `scrollTarget`-variable to the directive? Like this?
```html
<img [src]="youDefaultImage" [lazyLoad]="youImage" [scrollTarget]="scrollTarget">
```

**Comment by tjoskar** [comment]
> An example would have been great though.
Jepp, it would :) I may find some spare time this weekend to create one.

**Comment by thesunnypro** [comment]
I am using this code-

```
<div class="fileContents" #scrollableDiv id="scrollableDiv">
          <img
          *ngFor="let image of images"
          src="https://www.placecage.com/1000/1000"
          [errorImage]="errorImage"
          [lazyLoad]="image" [scrollTarget]="scrollTarget">
</div>
```

and in component- 

```
    errorImage = 'https://i.imgur.com/XkU4Ajf.png';
    scrollTarget = this.document.getElementById('scrollableDiv');

    images = [
      'https://hd.unsplash.com/photo-1441765425173-8fd330fb4a02',
      'https://hd.unsplash.com/photo-1451481454041-104482d8e284',
      'https://hd.unsplash.com/photo-1471070855862-324d571a1857',
      'https://hd.unsplash.com/photo-1415045550139-59b6fafc832f'
    ];
```

div with scrollableDiv id is my scrollable div.

**Comment by cpotter13** [comment]
I was having a similar issue just now and was able to get it working by setting the scrollTarget to the template reference variable as follows:

```
<div class="fileContents" #scrollableDiv>
  <img *ngFor="let image of images"
        src="https://www.placecage.com/1000/1000"
        [errorImage]="errorImage"
        [lazyLoad]="image"
        [scrollTarget]="scrollableDiv">
</div>
```
[Angular template syntax](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#ref-vars)

**Comment by tjoskar** [comment]
@thesunnypro I created a new [component](https://github.com/tjoskar/ng2-lazyload-image/blob/master/example/scroll-container.component.ts) in the example folder which shows two examples of how to use a scrollable container. Let me know if you run into any issues.

**Comment by tjoskar** [comment]
@thesunnypro, I closing this. Let me know if you run into any problems
